//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regions
    {
        public int ID_Region { get; set; }
        public string Klimat { get; set; }
        public string Relief { get; set; }
        public string Pochva { get; set; }
        public string FazOil { get; set; }
        public string SpawnOil { get; set; }
        public Nullable<int> KFWater { get; set; }
        public string MineralizeWater { get; set; }
        public string NameRegion { get; set; }
    }
}
